{% set name = "pyfd" %}
{% set version = "4.5.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: acb5226a60a33645780669fe1c0cca58d4e56aab8397c7e6c794d780f6096732

build:
  run_exports:
    - {{ pin_subpackage("pyfd", max_pin="x") }}
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.12.0
    - make  # [unix]
  host:
    - fd >=8.38.0
    - python
    - ctypesgen >=1.0.2
  run:
    - python

test:
  imports:
    - PyFd

about:
  home: https://git.ligo.org/virgo/virgoapp/PyFd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python binding for the Fd Library

extra:
  recipe-maintainers:
    - rhyspoulton
    - fcarbogn
